### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by benthamite** [org2blog/org2blog-importers#7]
Thanks for creating this importer. Unfortunately, I wasn't able to make it work. I replaced 

``` python
command = 'pandoc -r html -t org --no-wrap -'
```

with

``` python
command = 'pandoc -r html -t org --wrap=none -'
```

and

``` python
from urllib2 import unquote
```

with

``` python
from urllib.parse import unquote
```

but I get this traceback:

``` python-traceback
  File "wp_to_org2blog.py", line 207, in <module>
    blog_list = xml_to_list(args.in_file)
  File "wp_to_org2blog.py", line 88, in xml_to_list
    post['title'] = node.getElementsByTagName('title')[0].firstChild.data
AttributeError: 'NoneType' object has no attribute 'data'
```

I'm not a programmer so I don't know how to interpret this.

**Comment by punchagan** [comment]
The importer hasn't been updated in a long time, and I'm not surprised that you weren't able to get it to work. Thanks for your attempts to get it to work, and your notes. 

It looks like the Pull request [here](https://github.com/org2blog/org2blog-importers/pull/6) addresses all the issues you mentioned. Could you try using that and reporting if things work?  Or if you could share the XML that you are trying to import I could try helping you out.

**Comment by benthamite** [comment]
Thanks you for the quick reply.

I used that file (replacing `urllib2` with `urllib.parse`) but unfortunately I still was unable to make it work. Here's the traceback:

``` python
  File "/Users/pablostafforini/Dropbox/org/blog/wp_to_org2blog.py", line 228, in <module>
    blog_list = xml_to_list(args.in_file)
  File "/Users/pablostafforini/Dropbox/org/blog/wp_to_org2blog.py", line 126, in xml_to_list
    dom = minidom.parse(infile)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 67251, column 120
```

[Here is the xml file](https://www.dropbox.com/s/3mw9evtbm4i7hes/export.xml?dl=0) with the Wordpress export.

Thanks again for taking the time to help me.

**Comment by rolandog** [comment]
I have managed to get it to work, and I also handled the edge-case of choosing your links to be like https://example.com/?p=123

I'll try to add a commit to @hexmode's pull request.

I also ran into a `builtins.TypeError: must be str, not bytes` error.  Perhaps some functions now expect a different type of argument?

Additionally, I noticed a small indentation error that may result in some posts not being exported, so I also fixed that.

**Comment by punchagan** [comment]
Thanks @rolandog and apologies @benthamite for dropping the ball on this!

**Comment by rolandog** [comment]
No worries @punchagan .  Here's the code if anyone want's to view it or use it:

But I can try to submit as a different pull request, if needed:

<details>
<summary>fixed indentation error, added case for '?p=' URLs, formatted with black</summary>

```python
#!/usr/bin/env python

"""wp_to_org2blog.py: Convert wordpress.xml to org2blog posts.

To create and export of Posts and nothing else:

- Log in to your WordPress site
- Dashboard, Tools, Export
- Posts
  - Categories: All
  - Authors: All
  - Date range start, end: "Start Date", "End Date"
    - Returns every post
  - Status: All
- Direct download and add.

"""

__author__ = "Puneeth Chaganti"
__copyright__ = "Copyright 2011"
__license__ = "GPLv3"
__version__ = "0.7"
__email__ = "punchagan@muse-amuse.in"


import os
import re
import argparse
import logging


from time import strptime, strftime
from xml.dom import minidom
from subprocess import Popen, PIPE, SubprocessError
from shlex import split
from urllib.parse import unquote

SUBTREE_TEMPLATE = u"""\
%(stars)s %(title)s %(tags)s
%(space)s :PROPERTIES:
%(space)s :POSTID: %(id)s
%(space)s :POST_DATE: %(date)s
%(space)s :CATEGORY: %(categories)s
%(space)s :END:

%(space)s %(text)s

"""

BUFFER_TEMPLATE = u"""\
#+POSTID: %(id)s
#+DATE: %(date)s
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: %(categories)s
#+TAGS: %(tags)s
#+TITLE: %(title)s

%(text)s


"""


def html_to_org(html):
    """Converts a html snippet to an org-snippet."""

    command = "pandoc -r html -t org --wrap=none -"
    args = split(command)

    proc = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, error = proc.communicate(html)

    if (proc.returncode != 0) or (error != b""):
        errormessage = """%s exited with return code %s and error %s when parsing:
            %s"""
        raise SubprocessError(errormessage % (args[0], proc.returncode, error, html))

    return output


def get_first_child_data(node, tag_name):
    """Try to retrieve the data contained at a node's tag's firstChild."""
    try:
        return node.getElementsByTagName(tag_name)[0].firstChild.data
    except (AttributeError, IndexError):
        return None


def node_to_post(node):
    """Takes an XML node from the export and converts it to a dict"""

    # key: (XML) tag_name
    key_map = {
        "title": "title",
        "link": "link",
        "date": "pubDate",
        "author": "dc:creator",
        "id": "wp:post_id",
        "text": "content:encoded",
        "post_name": "wp:post_name",
    }
    post = dict()

    for key, tag_name in key_map.items():
        post[key] = get_first_child_data(node, tag_name)

    try:
        if int(post["id"]) % 10 == 0:
            logging.getLogger().info("Processing post #%s", post["id"])
    except ValueError:
        logging.getLogger().debug("Processing post #%s", post["id"])

    if post["text"] is not None:
        post["text"] = post["text"].replace("\r\n", "\n")
        post["text"] = post["text"].replace("\n", "#$NEWLINE-MARKER$#")
        post["text"] = html_to_org(post["text"].encode("utf8")).decode("utf8")
        post["text"] = post["text"].replace("#$NEWLINE-MARKER$#", "\n")
    else:
        post["text"] = ""

    # Get the tags and categories
    post["tags"] = list()
    post["categories"] = list()

    for element in node.getElementsByTagName("category"):
        domain, name = element.getAttribute("domain"), element.getAttribute("nicename")

        if name and domain and ("tag" in domain or "category" in domain):
            name = element.firstChild.data
            domain = "tags" if "tag" in domain else "categories"
            post[domain].append(name)

    return post


def xml_to_list(infile):
    """Return a list containing all the posts from the infile.
    Each post is a dictionary.
    """

    dom = minidom.parse(infile)

    blog = list()  # list that will contain all posts

    for node in dom.getElementsByTagName("item"):

        post = node_to_post(node)

        for domain in ["tags", "categories"]:
            post[domain] = sorted(set(post[domain]))

        # FIXME - wp:attachment_url could be use to download attachments

        blog.append(post)

    return blog


def link_to_file(link, post_name=None):
    """Gets filename from wordpress url."""

    name = None
    check_for_letters = re.compile("[a-z]+", re.IGNORECASE)
    try:
        if (post_name != "") and (post_name is not None):
            if check_for_letters.match(post_name) is not None:
                name = post_name
            else:
                name = None

        if name is None:
            if "?p=" in link:
                name = link.split("?p=")[-1]
            else:
                name = link.split("/")[-2]

        name = "%s.org" % unquote(name)
    # occasionally, some encoding errors may seep through
    except TypeError:
        logging.getLogger().debug("Error getting file link for %s, %s", link, post_name)

    return name


def parse_date(date, date_format):
    """Change wp date format to a different format."""

    if date is not None:
        date = date.split("+")[0].strip()
        date = strptime(date, "%a, %d %b %Y %H:%M:%S")
        date = strftime(date_format, date)

    return date


def blog_to_org(blog_list, name, level, buffer, prefix):
    """Converts a blog-list into an org file."""

    space = " " * level
    stars = "*" * level

    tag_sep = ", "
    cat_sep = ", "

    template_parts = dict()

    if buffer:
        template = BUFFER_TEMPLATE
    else:
        template = SUBTREE_TEMPLATE
        tag_sep = ":"
        org_file = open("%s.org" % name, "wb")

    for post in blog_list:
        post["tags"] = tag_sep.join(post["tags"])
        if tag_sep == ":":
            post["tags"] = ":" + post["tags"] + ":"
        post["categories"] = cat_sep.join(post["categories"])
        date_wp_fmt = post["date"]
        post["date"] = parse_date(date_wp_fmt, "[%Y-%m-%d %a %H:%M]")

        if not buffer:
            post["text"] = post["text"].replace("\n", "\n %s" % space)

        template_parts.update(**post)
        template_parts.update(space=space)
        template_parts.update(stars=stars)
        post_output = template % template_parts

        if buffer:
            if prefix:
                file_name = "%s-%s" % (
                    parse_date(date_wp_fmt, "%Y-%m-%d"),
                    link_to_file(post["link"], post["post_name"]),
                )
            else:
                file_name = link_to_file(post["link"], post["post_name"])
            if not os.path.exists(name):
                os.mkdir(name)
            else:
                org_file = open(os.path.join(name, file_name), "wb")
                org_file.write(post_output.encode("utf8"))
                org_file.close()
        else:
            org_file.write(post_output.encode("utf8"))

    org_file.close()


def main():
    """Main function; meant to be executed when the script is called from CLI."""
    parser = argparse.ArgumentParser(
        description="Convert wordpress.xml to org2blog posts."
    )

    parser.add_argument("in_file", help="the input xml file exported from WP")
    parser.add_argument(
        "--buffer",
        action="store_true",
        help="enable to obtain a separate file for each post",
    )
    parser.add_argument(
        "--prefix-date",
        action="store_true",
        help="prefix a date to the post files, when --buffer",
    )
    parser.add_argument(
        "-l",
        "--level",
        type=int,
        default=1,
        help="level of the subtree when exporting to SUBTREE",
    )
    parser.add_argument(
        "-o",
        "--out-file",
        default="org-posts",
        help="file or directory name for output",
    )

    args = parser.parse_args()

    logging_format = "%(message)s"
    logging.basicConfig(format=logging_format, level=logging.INFO)
    logger = logging.getLogger()

    logger.warning("Parsing xml ...")
    blog_list = xml_to_list(args.in_file)

    logger.warning("Writing posts...")
    blog_to_org(blog_list, args.out_file, args.level, args.buffer, args.prefix_date)

    logger.warning("Done!")


if __name__ == "__main__":
    main()

```

</details>

**Comment by benthamite** [comment]
Thank you for taking the time to look into this, @rolandog.

Unfortunately, I still get an error.

``` python
Traceback (most recent call last):
  File "script.py", line 297, in <module>
    main()
  File "script.py", line 288, in main
    blog_list = xml_to_list(args.in_file)
  File "script.py", line 141, in xml_to_list
    dom = minidom.parse(infile)
  File "/Users/pablostafforini/.pyenv/versions/3.8.5/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/Users/pablostafforini/.pyenv/versions/3.8.5/lib/python3.8/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/Users/pablostafforini/.pyenv/versions/3.8.5/lib/python3.8/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 67251, column 120
```
I'm using the [same xml file](https://www.dropbox.com/s/3mw9evtbm4i7hes/export.xml?dl=0) as before. Do you have thoughts on what might be going on?

**Comment by rolandog** [comment]
Ahh, sorry for the delay in my response.  I was cooking dinner :man_cook:.

I forgot to test against your file, and I assumed my own blog's export would be representative.

I'll look into it to see if I can catch what is triggering that error.

**Comment by rolandog** [comment]
A quick modification to the code:
<details>
<summary>Updated code</summary>

```python3
#!/usr/bin/env python

"""wp_to_org2blog.py: Convert wordpress.xml to org2blog posts.

To create and export of Posts and nothing else:

- Log in to your WordPress site
- Dashboard, Tools, Export
- Posts
  - Categories: All
  - Authors: All
  - Date range start, end: "Start Date", "End Date"
    - Returns every post
  - Status: All
- Direct download and add.

"""

__author__ = "Puneeth Chaganti"
__copyright__ = "Copyright 2011"
__license__ = "GPLv3"
__version__ = "0.7"
__email__ = "punchagan@muse-amuse.in"


import os
import re
import argparse
import logging


from time import strptime, strftime
from xml.dom import minidom
from xml.parsers.expat import ExpatError
from subprocess import Popen, PIPE, SubprocessError
from shlex import split
from urllib.parse import unquote

SUBTREE_TEMPLATE = u"""\
%(stars)s %(title)s %(tags)s
%(space)s :PROPERTIES:
%(space)s :POSTID: %(id)s
%(space)s :POST_DATE: %(date)s
%(space)s :CATEGORY: %(categories)s
%(space)s :END:

%(space)s %(text)s

"""

BUFFER_TEMPLATE = u"""\
#+POSTID: %(id)s
#+DATE: %(date)s
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: %(categories)s
#+TAGS: %(tags)s
#+TITLE: %(title)s

%(text)s


"""


def html_to_org(html):
    """Converts a html snippet to an org-snippet."""

    command = "pandoc -r html -t org --wrap=none -"
    args = split(command)

    proc = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, error = proc.communicate(html)

    if (proc.returncode != 0) or (error != b""):
        errormessage = """%s exited with return code %s and error %s when parsing:
            %s"""
        raise SubprocessError(errormessage % (args[0], proc.returncode, error, html))

    return output


def get_first_child_data(node, tag_name):
    """Try to retrieve the data contained at a node's tag's firstChild."""
    try:
        return node.getElementsByTagName(tag_name)[0].firstChild.data
    except (AttributeError, IndexError):
        return None


def node_to_post(node):
    """Takes an XML node from the export and converts it to a dict"""

    # key: (XML) tag_name
    key_map = {
        "title": "title",
        "link": "link",
        "date": "pubDate",
        "author": "dc:creator",
        "id": "wp:post_id",
        "text": "content:encoded",
        "post_name": "wp:post_name",
    }
    post = dict()

    for key, tag_name in key_map.items():
        post[key] = get_first_child_data(node, tag_name)

    try:
        if int(post["id"]) % 10 == 0:
            logging.getLogger().info("Processing post #%s", post["id"])
    except ValueError:
        logging.getLogger().debug("Processing post #%s", post["id"])

    if post["text"] is not None:
        post["text"] = post["text"].replace("\r\n", "\n")
        post["text"] = post["text"].replace("\n", "#$NEWLINE-MARKER$#")
        post["text"] = html_to_org(post["text"].encode("utf8")).decode("utf8")
        post["text"] = post["text"].replace("#$NEWLINE-MARKER$#", "\n")
    else:
        post["text"] = ""

    # Get the tags and categories
    post["tags"] = list()
    post["categories"] = list()

    for element in node.getElementsByTagName("category"):
        domain, name = element.getAttribute("domain"), element.getAttribute("nicename")

        if name and domain and ("tag" in domain or "category" in domain):
            name = element.firstChild.data
            domain = "tags" if "tag" in domain else "categories"
            post[domain].append(name)

    return post


def xml_to_list(infile):
    """Return a list containing all the posts from the infile.
    Each post is a dictionary.
    """

    try:
        dom = minidom.parse(infile)
    except ExpatError as err:
        print("Error while parsing %s: %s" % (infile, err))
        raise

    blog = list()  # list that will contain all posts

    for node in dom.getElementsByTagName("item"):

        post = node_to_post(node)

        for domain in ["tags", "categories"]:
            post[domain] = sorted(set(post[domain]))

        # FIXME - wp:attachment_url could be use to download attachments

        blog.append(post)

    return blog


def link_to_file(link, post_name=None):
    """Gets filename from wordpress url."""

    name = None
    check_for_letters = re.compile("[a-z]+", re.IGNORECASE)
    try:
        if (post_name != "") and (post_name is not None):
            if check_for_letters.match(post_name) is not None:
                name = post_name
            else:
                name = None

        if name is None:
            if "?p=" in link:
                name = link.split("?p=")[-1]
            else:
                name = link.split("/")[-2]

        name = "%s.org" % unquote(name)
    # occasionally, some encoding errors may seep through
    except TypeError:
        logging.getLogger().debug("Error getting file link for %s, %s", link, post_name)

    return name


def parse_date(date, date_format):
    """Change wp date format to a different format."""

    if date is not None:
        date = date.split("+")[0].strip()
        date = strptime(date, "%a, %d %b %Y %H:%M:%S")
        date = strftime(date_format, date)

    return date


def blog_to_org(blog_list, name, level, buffer, prefix):
    """Converts a blog-list into an org file."""

    space = " " * level
    stars = "*" * level

    tag_sep = ", "
    cat_sep = ", "

    template_parts = dict()

    if buffer:
        template = BUFFER_TEMPLATE
    else:
        template = SUBTREE_TEMPLATE
        tag_sep = ":"
        org_file = open("%s.org" % name, "wb")

    for post in blog_list:
        post["tags"] = tag_sep.join(post["tags"])
        if tag_sep == ":":
            post["tags"] = ":" + post["tags"] + ":"
        post["categories"] = cat_sep.join(post["categories"])
        date_wp_fmt = post["date"]
        post["date"] = parse_date(date_wp_fmt, "[%Y-%m-%d %a %H:%M]")

        if not buffer:
            post["text"] = post["text"].replace("\n", "\n %s" % space)

        template_parts.update(**post)
        template_parts.update(space=space)
        template_parts.update(stars=stars)
        post_output = template % template_parts

        if buffer:
            if prefix:
                file_name = "%s-%s" % (
                    parse_date(date_wp_fmt, "%Y-%m-%d"),
                    link_to_file(post["link"], post["post_name"]),
                )
            else:
                file_name = link_to_file(post["link"], post["post_name"])
            if not os.path.exists(name):
                os.mkdir(name)
            else:
                org_file = open(os.path.join(name, file_name), "wb")
                org_file.write(post_output.encode("utf8"))
                org_file.close()
        else:
            org_file.write(post_output.encode("utf8"))

    org_file.close()


def main():
    """Main function; meant to be executed when the script is called from CLI."""
    parser = argparse.ArgumentParser(
        description="Convert wordpress.xml to org2blog posts."
    )

    parser.add_argument("in_file", help="the input xml file exported from WP")
    parser.add_argument(
        "--buffer",
        action="store_true",
        help="enable to obtain a separate file for each post",
    )
    parser.add_argument(
        "--prefix-date",
        action="store_true",
        help="prefix a date to the post files, when --buffer",
    )
    parser.add_argument(
        "-l",
        "--level",
        type=int,
        default=1,
        help="level of the subtree when exporting to SUBTREE",
    )
    parser.add_argument(
        "-o",
        "--out-file",
        default="org-posts",
        help="file or directory name for output",
    )

    args = parser.parse_args()

    logging_format = "%(message)s"
    logging.basicConfig(format=logging_format, level=logging.INFO)
    logger = logging.getLogger()

    logger.warning("Parsing xml ...")
    blog_list = xml_to_list(args.in_file)

    logger.warning("Writing posts...")
    blog_to_org(blog_list, args.out_file, args.level, args.buffer, args.prefix_date)

    logger.warning("Done!")


if __name__ == "__main__":
    main()

```
</details>

Allows us to catch the error:

<details>

<summary>new error message in console</summary>

```console

user@computer:~/org2blog$ python3 wp_to_org2blog.py --buffer -o benthamite export.xml
Parsing xml ...
Error while parsing export.xml: not well-formed (invalid token): line 67251, column 120
Traceback (most recent call last):
  File "/home/rolandog/Downloads/software/org2blog/org2blog-importers/wp_to_org2blog.py", line 302, in <module>
    main()
  File "/home/rolandog/Downloads/software/org2blog/org2blog-importers/wp_to_org2blog.py", line 293, in main
    blog_list = xml_to_list(args.in_file)
  File "/home/rolandog/Downloads/software/org2blog/org2blog-importers/wp_to_org2blog.py", line 143, in xml_to_list
    dom = minidom.parse(infile)
  File "/usr/lib/python3.9/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 67251, column 120

```

</details>

It may seem, as per [looking for the same error elsewhere](https://stackoverflow.com/q/34765260/297570), that the XML file could be malformed or may have some errors that could prevent the proper parsing.

In this case, the error message now reads:

> Error while parsing export.xml: not well-formed (invalid token): line 67251, column 120

<details>
<summary>XML with encoding errors</summary>

```xml

<content:encoded><![CDATA[<blockquote>[O]ur moral judgments are less reliable than many would hope, and this has specific implications for methodology in normative ethics. Three sources of evidence indicate that our intuitive ethical judgments are less reliable than we might have hoped: a historical record of accepting morally absurd social practices; a scientic record showing that our intuitive judgments are systematically governed by a host of heuristics, biases, and irrelevant factors; and a philosophical record showing deep, probably unresolvable, inconsistencies in common moral convictions. I argue that this has the following implications for moral theorizing: we should trust intuitions less; we should be especially suspicious of intuitive judgments that t a bias pattern, even when we are intuitively condent that these judgments are not a simple product of the bias; we should be especially suspicious of intuitions that are part of inconsistent sets of deeply held convictions; and we should evaluate views holistically, thinking of entire classes of judgments that they get right or wrong in broad contexts, rather than dismissing positions on the basis of a small number of intuitive counterexamples.</blockquote>

Nick Beckstead, <em>On the Overwhelming Importance of Shaping the Far Future</em>, doctoral dissertation, University of Rutgers, New Brunswick, 2013, p. 19]]></content:encoded>

```

</details>

And, after fixing the 4 encoding errors:

<details>

<summary>XML without encoding errors</summary>

```xml

<content:encoded><![CDATA[<blockquote>[O]ur moral judgments are less reliable than many would hope, and this has specific implications for methodology in normative ethics. Three sources of evidence indicate that our intuitive ethical judgments are less reliable than we might have hoped: a historical record of accepting morally absurd social practices; a scientific record showing that our intuitive judgments are systematically governed by a host of heuristics, biases, and irrelevant factors; and a philosophical record showing deep, probably unresolvable, inconsistencies in common moral convictions. I argue that this has the following implications for moral theorizing: we should trust intuitions less; we should be especially suspicious of intuitive judgments that fit a bias pattern, even when we are intuitively confident that these judgments are not a simple product of the bias; we should be especially suspicious of intuitions that are part of inconsistent sets of deeply held convictions; and we should evaluate views holistically, thinking of entire classes of judgments that they get right or wrong in broad contexts, rather than dismissing positions on the basis of a small number of intuitive counterexamples.</blockquote>

Nick Beckstead, <em>On the Overwhelming Importance of Shaping the Far Future</em>, doctoral dissertation, University of Rutgers, New Brunswick, 2013, p. 19]]></content:encoded>

```

</details>

Which allows us to successfully execute the program:

<details>

<summary>successful execution of parsing</summary>

```console

user@computer:~/org2blog$ python3 wp_to_org2blog.py --buffer -o benthamite export.xml
Parsing xml ...
Processing post #10
Processing post #3290
Processing post #3560
Processing post #20
Processing post #40
Processing post #50
Processing post #60
Processing post #70
Processing post #100
Processing post #120
Processing post #130
Processing post #150
Processing post #160
Processing post #190
Processing post #220
Processing post #250
Processing post #270
Processing post #280
Processing post #290
Processing post #300
Processing post #310
Processing post #330
Processing post #340
Processing post #350
Processing post #370
Processing post #390
Processing post #400
Processing post #410
Processing post #420
Processing post #430
Processing post #440
Processing post #460
Processing post #470
Processing post #480
Processing post #490
Processing post #510
Processing post #520
Processing post #530
Processing post #540
Processing post #550
Processing post #560
Processing post #570
Processing post #580
Processing post #590
Processing post #600
Processing post #610
Processing post #620
Processing post #630
Processing post #640
Processing post #650
Processing post #660
Processing post #670
Processing post #680
Processing post #690
Processing post #700
Processing post #30
Processing post #710
Processing post #80
Processing post #90
Processing post #110
Processing post #170
Processing post #180
Processing post #200
Processing post #210
Processing post #230
Processing post #240
Processing post #260
Processing post #320
Processing post #380
Processing post #500
Processing post #720
Processing post #730
Processing post #740
Processing post #750
Processing post #760
Processing post #770
Processing post #780
Processing post #790
Processing post #800
Processing post #810
Processing post #820
Processing post #840
Processing post #850
Processing post #860
Processing post #870
Processing post #880
Processing post #890
Processing post #900
Processing post #910
Processing post #930
Processing post #970
Processing post #1180
Processing post #1270
Processing post #1200
Processing post #1210
Processing post #1260
Processing post #1350
Processing post #1480
Processing post #1500
Processing post #1650
Processing post #1620
Processing post #1760
Processing post #1940
Processing post #2030
Processing post #2110
Processing post #2170
Processing post #2180
Processing post #2200
Processing post #2210
Processing post #2260
Processing post #2270
Processing post #2300
Processing post #2310
Processing post #2420
Processing post #2460
Processing post #2490
Processing post #2510
Processing post #2550
Processing post #2580
Processing post #2590
Processing post #2600
Processing post #2650
Processing post #2690
Processing post #2710
Processing post #2750
Processing post #2760
Processing post #2790
Processing post #2800
Processing post #2850
Processing post #2870
Processing post #2880
Processing post #2930
Processing post #2940
Processing post #2960
Processing post #2980
Processing post #3000
Processing post #3010
Processing post #3030
Processing post #3040
Processing post #3070
Processing post #3090
Processing post #3140
Processing post #3150
Processing post #3190
Processing post #3220
Processing post #2920
Processing post #830
Processing post #1840
Processing post #3480
Processing post #3490
Processing post #3510
Processing post #3550
Processing post #3590
Processing post #3620
Processing post #3630
Processing post #3670
Processing post #3760
Processing post #3890
Processing post #3900
Processing post #3910
Writing posts...
Done!

```

</details>

**Comment by rolandog** [comment]
Btw, @punchagan , If you approve @hexmode's #6 , I can submit my commits as a different PR.

**Comment by benthamite** [comment]
Fantastic—it works perfectly now. I really appreciate your help, @rolandog!

**Comment by rolandog** [comment]
Glad it worked and to have been of help, @benthamite !

**Comment by rolandog** [comment]
@punchagan , I have re-worked the commits to clarify what was added at each step, and hopefully this is able to be merged so that more users can be helped in their migration.
